---
title: "統計データ解析"
subtitle: "第8講 実習"
date: "`r Sys.Date()`"
format:
    html: 
      toc: true
      html-math-method: katex
      self-contained: true
      grid: 
        margin-width: 350px
execute: 
  echo: true
  warning: false
reference-location: margin
citation-location: margin
tbl-cap-location: margin
fig-cap-location: margin
editor: visual
editor_options: 
  chunk_output_type: console
---

## 準備

以下で利用する共通パッケージを読み込む．

```{r}
library(conflicted) # 関数名の衝突を警告
conflicts_prefer(   # 優先的に使う関数を指定
  dplyr::filter(),
  dplyr::select(),
  dplyr::lag(),
  )
library(tidyverse)  
library(MASS)
library(broom)      # 解析結果を tibble 形式に集約
library(gt)         # 表の作成
library(gtsummary)  # 分析結果の表の作成
library(ggfortify)  # biplot表示のため
```

## 線形判別

### 問題

東京の気候データを用いて以下の分析を行いなさい．

-   9月と10月の気温と湿度のデータを抽出する．

    ``` r
    tw_data <- read_csv("data/tokyo_weather.csv") 
    tw_subset  <- tw_data |>
        filter(month %in% c(9,10)) |>
        select(temp, humid, month) |>
        mutate(month = as_factor(month)) # 月を因子化
    ```

-   半分のデータを用いて線形判別関数を構成し，残りのデータを用いて判別を行う．

    ``` r
    idx <- seq(2, 60, by = 2)
    tw_train <- tw_subset[ idx,] # 訓練データ
    tw_test  <- tw_subset[-idx,] # 試験データ
    tw_lda <- lda(month ~ temp + humid, data = tw_train) # 線形判別関数の構成
    tw_lda_fitted <- predict(tw_lda) # 判別関数によるクラス分類結果の取得
    tw_lda_predict <- predict(tw_lda, newdata = tw_test) # 新しいデータの予測
    ```

```{r}

```

## 2次判別

### 問題

東京の気候データを用いて以下の分析を行いなさい．

-   前問と同様な設定で2次判別を行いなさい．

    ``` r
    tw_qda <- qda(month ~ temp + humid, data = tw_train) # 2次判別関数の構成
    tw_qda_fitted <- predict(tw_qda)                     # 判別関数によるクラス分類結果の取得
    tw_qda_predict <- predict(tw_qda, newdata = tw_test) # 新しいデータの予測
    ```

-   別の月や変数を用いて判別分析を行いなさい．

```{r}

```

## 多値判別

### 問題

東京の気候データを用いて以下の分析を行いなさい．

-   9月，10月，11月の気温と湿度のデータを用いて判別関数を作成しなさい．

    ``` r
    tw_subset  <- tw_data |>
        filter(month %in% c(9,10,11)) |>
        select(temp, humid, month) |>
        mutate(month = as_factor(month))
    ```

-   別の月や変数を用いて判別分析を行いなさい．

    ``` r
    #' 雨の有無を識別する例
    tw_subset2 <- tw_data |>
        mutate(rain = factor(rain > 0),
               month = as_factor(month)) |>     # 雨の有無でラベル化する
        select(rain, temp, solar, wind, month)
    tw_lda2 <- lda(rain ~ ., data = tw_subset2) # 'rain' をそれ以外で判別
    ```

```{r}

```
